### ISSUE TITLE
Full length definitions

### ISSUE THREAD

**Issue by hallundbaek** [kuhumcst/DanNet#137]
Quite often, the definitions provided are cut short before actually defining the word in question.

Examples:

- **magnet**: "genstand, fx et redskab el. en komponent, som fysi…"
- **kringle**: "kage el. brød af form som en stang hvis ender er b…"
- **ontologi**: "retning inden for filosofien som beskæftiger sig m…"
- **adel**: "samfundsklasse bestående af personer som har meget…"

It hampers the fields value quite drastically, and in some cases like the above, the actual definition is lost.

**Comment by simongray** [comment]
You can BTW go to the original cases in almost all cases by visiting either the `LexicalEntry` or the `LexicalSense` of the synset in question, e.g. for https://wordnet.dk/dannet/data/sense-21019353 check out the value of `dns:source`.
